### ISSUE TITLE
Not every entity can perform a role in the ecosystem.

### ISSUE THREAD

**Issue by RieksJ** [w3c/vc-data-model#463]
The definition of "entity" says: "A thing with distinct and independent existence, such as a person, organization, concept, or device. An entity can perform one or more roles in the ecosystem." 

However, a concept, while being one of the examples of a thing, cannot perform any of the roles in the ecosystem. I suggest to leave the last sentence out and just stick with the definition.

**Comment by talltree** [comment]
+1.

**Comment by jandrieu** [comment]
The goal of that sentence is to make it clear that those entity performing a given role, such as an Issuer, may also perform the other roles in the system. So I'm hesitant to cut out the last sentence.

That said, I agree. The definition could be improved. Personally, thinking of concepts as entities makes no sense to me, as "independent existence" doesn't seem to be met for ideas, which by their nature are dependent on the sentient being thinking the concept, or at best, the representation of the idea in words or bits.  

This prompts me to re-invite you to suggest a work item for the CCG about terminology. I'm keen to have a more effective solution to approaching these questions. The bikeshedding approach is historically a mess.

**Comment by RieksJ** [comment]
I prefer to distinguish between standards documents (that serve the purpose of different people doing or knowing stuff in the same way) and documents that serve educational/awareness purposes, that can be more elaborate. I hate having to go through educational texts when I'm just looking for what is commonly agreed upon. So I suggest to strike the last sentence, because this is a standard. If we need to educate people about VCs, we should do so in (a) separate document(s).

The 2nd paragraph of @jandrieu touches the very basics of semantics and knowledge, which some people refer to as 'philosophical', and which I am convinced we should understand really well if we want to do a good job on VCs. And that is the notion than things only exist because there is a sentient being that has knowledge of that existence. In other words: 'existence' is subjective. For example, I only exist because there are sentient beings (such as you) that have knowledge of my existence. I am not saying that you need to agree on this (it took me a while to accept it), but accepting this premise has helped us a lot in our thinking, in particular about the semantics of 'subject', 'identifier', 'subject-identifier' and the like. 

What's CCG?

**Comment by jandrieu** [comment]
Ok. That's a great argument, @RieksJ, I withdraw my opposition.

As for subjectivity, you raise a delightful rabbit hole I didn't intend to open up. *Ideas* are, IMO, by definition subjective, regardless of whether or not people or things are objective in any physical sense of the word. One positive consequence of your position however, is already nicely embodied in the VC architecture, namely that VCs are *always* statements by an explicit author and never objective "facts" with implied authorship. That is, a VC says "Joe says 'The sky is blue'" rather than "The sky is blue". This separation from factual "objective" claims to source-based "subjective" claims is vital to understanding what is, in fact, verifiable in a verifiable claim. It isn't the fact, it is the utterance by an author.

The CCG is the Credentials Community Group, where much of the DID and VC work has been incubated.  https://www.w3.org/community/credentials/ As a community group, it has a bit more leeway for exploratory work by the community compared to working groups that have specific specifications with specific deadlines. I think it is a natural fit for the terminology process work you suggested at RWOT.

Feel free to email me directly if you'd like.

**Comment by David-Chadwick** [comment]
I agree that "concept" should be removed from the set of things that can participate in the eco-system. I also think the second sentence about one or more roles is valuable, since it adds value, but suggest replacing can with may.

**Comment by RieksJ** [comment]
@David-Chadwick : while I agree that no 'concept' should participate in the eco-system, concepts do belong to the class of entities, and therefore 'concept' is a valid example of an entity. It is also a nice example of why we also need terms to distinguish between entities that do and those that do not have additional characteristics, such as whether or not they can participate in the eco-system.

I think that 'concept' should remain because it alludes to the possibility that a concept, or an idea, can be the subject of a claim.

**Comment by RieksJ** [comment]
@jandrieu: I'm so happy with your statement "that VCs are always statements by an explicit author and never objective "facts" with implied authorship" as I feel that it cannot be overemphasized. It seems to me that only a few people seem to grasp what it means that all this stuff is subjective, and a natural consequence of acknowledging that the world we live is fundamentally decentralized. IMHO, too many people have trouble in chaning their mental thinking from a centralized ('geocentric') position to a decentralized one ('heliocentric'?). Wonder what you think about #467, that is an attempt to bring this a bit further.

**Comment by David-Chadwick** [comment]
So we have two different entities (at least)
1. claims: that can be about concepts or things
2. roles: which participate in the eco-system
Lets not mix up the two because these entities are not the same sets of things.

**Comment by David-Chadwick** [comment]
P.s. I think this is tied to #467

**Comment by chaals** [comment]
A concept can perform the role of "claim".

That said, it appears that the goal of the definition in the specification is to restrict the meaning used to things that *do* perform a role in the ecosystem. Perhaps it would be clearer to say in the description:

> A thing with distinct and independent existence, such as a person, organization, concept, or device, **that performs** one or more roles in the ecosystem

In any event this is an editorial issue - the terminology section is non-normative and this does not materially affect implementation or conformance.

**Comment by jandrieu** [comment]
I think @chaals gets it right.

I'd like to flesh out these distinctions @RieksJ and suggest we spin up an effort at the CCG, including the terminological issue #467 . 

I suggest we avoid these issues for the proposed CR, although @chaals editorial suggestion I think fixes this particular section in a way that doesn't lose the original intention.

**Comment by David-Chadwick** [comment]
Fixed in PR#504

**Comment by RieksJ** [comment]
@David-Chadwick 

> Fixed in PR#504

PR#504 didn't fix the definition of 'entity' that started this discussion. If the suggestion I did isn't what is called for, you might want to follow [your proposal](https://github.com/w3c/vc-data-model/issues/463#issuecomment-474235469), and change the word 'can' in the definition into 'may' or 'might'.

**Comment by David-Chadwick** [comment]
@RieksJ You are right. My PR followed the suggestions of @jandrieu and @chaals but looking again at this, I no longer agree with @chaals because claim is not a role in the system. All the roles are specified in section 1.2, and claim is not there. So concept should be removed and then there is no need for "may" in the definition of entity.

**Comment by msporny** [comment]
PR #504 has been reviewed by multiple people and merged. I did further alignment around entity/role language. The next step is to see if the WG agrees with this change.

**Comment by stonematt** [comment]
Resolved on VCWG call 4/16/2019.
RESOLVED: Issue #463 is addressed by PR #504, which makes non-normative changes to updated the definition of an entity requested by the reviewer. The PR has been approved by multiple parties and has been merged. Issue #463 should be closed.

Plan to close in 7days
